# Generated by Django 3.2.5 on 2021-08-14 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0002_womancomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='womanimage',
            options={'ordering': ['id'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='womancomment',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='icon.woman'),
        ),
    ]
