# Generated by Django 3.2.5 on 2021-08-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0004_auto_20210815_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womancomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_comments', to='icon.woman'),
        ),
    ]
