# Generated by Django 3.2.5 on 2021-08-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0006_auto_20210816_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='womanlike',
            name='text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
