# Generated by Django 3.2.5 on 2021-08-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0007_womanlike_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='womanlike',
            name='text',
        ),
    ]
