# Generated by Django 3.2.5 on 2021-08-18 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0012_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
