# Generated by Django 3.2.5 on 2021-08-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0013_delete_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='womancomment',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='likedcomment',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
