# Generated by Django 3.2.5 on 2021-08-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0016_alter_likedcomment_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='woman',
            name='views',
        ),
        migrations.AddField(
            model_name='woman',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='icon.IpModel'),
        ),
    ]
