# Generated by Django 3.2.7 on 2021-09-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0017_auto_20210921_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/Data%y/%m/%d/'),
        ),
    ]
