# Generated by Django 3.2.5 on 2021-08-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0017_auto_20210821_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmodel',
            name='post_news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icon.woman'),
        ),
    ]
