# Generated by Django 3.2.5 on 2021-08-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0018_ipmodel_post_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipmodel',
            name='post_news',
        ),
    ]
