# Generated by Django 3.2.7 on 2021-09-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0018_alter_woman_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='cat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='icon.category', verbose_name='Category'),
        ),
    ]
