# Generated by Django 3.2.5 on 2021-08-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0019_remove_ipmodel_post_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woman',
            name='views',
        ),
        migrations.AddField(
            model_name='ipmodel',
            name='post_news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip', to='icon.woman'),
        ),
    ]
