# Generated by Django 3.2.5 on 2021-09-03 06:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0021_auto_20210825_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
