# Generated by Django 3.2.5 on 2021-09-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0022_woman_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woman',
            name='text',
        ),
    ]
